[package]
name = "events"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.0.0", features = ["full"]}
futures-channel = "*"
tokio-tungstenite = "*"
futures-locks = "*"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
url = "*"